#!/bin/bash

PARENT=$(pwd)
TOOLS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$TOOLS_DIR/git-config"
source "$TOOLS_DIR/project-list"
if [[ -e $PARENT/git-config ]]; then
  source "$PARENT/git-config"
fi
if [[ -e $PARENT/project-list ]]; then
  source "$PARENT/project-list"
fi

for projectName in $MIFOSIO_PROJECTS
do
  echo "========================= Add upstream for $projectName"
  if [[ -d $PARENT/$projectName ]]; then
    cd $PARENT/$projectName
    git remote add upstream $MIFOSIO_REPO_BASE/$projectName
    cd $PARENT
  fi
done
