#!/bin/bash

PARENT=$(pwd)
TOOLS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$TOOLS_DIR/git-config"
source "$TOOLS_DIR/project-list"

for projectName in $MIFOSIO_PROJECTS
do
  echo "========================= Building $projectName"
  if [[ -d $PARENT/$projectName ]]; then
    cd $PARENT/$projectName
    chmod +x gradlew
    /bin/bash ./gradlew publishToMavenLocal
    cd $PARENT
  fi
done

for projectName in $MY_PROJECTS
do
  echo "========================= Building $projectName"
  if [[ -d $PARENT/$projectName ]]; then
    cd $PARENT/$projectName
    chmod +x gradlew
    /bin/bash ./gradlew publishToMavenLocal
    cd $PARENT
  fi
done
