#!/bin/bash

if [[ -z "$1" ]]; then
  echo "please specify branch"
  exit
fi
BRANCH_NAME="$1"

PARENT=$(pwd)
TOOLS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$TOOLS_DIR/splitter"
source "$TOOLS_DIR/git-config"
source "$TOOLS_DIR/project-list"
if [[ -e $PARENT/git-config ]]; then
  source "$PARENT/git-config"
fi
if [[ -e $PARENT/project-list ]]; then
  source "$PARENT/project-list"
fi

for projectName in $PROJECTS
do
  unset projectDesc
  declare -a projectDesc
  split_line projectDesc $projectName

  echo "========================= Add upstream for ${projectDesc[0]}"
  if [[ -d "$PARENT/${projectDesc[1]}" ]]; then
    cd "$PARENT/${projectDesc[1]}"
    git stash save
    if [[ $(git branch -a | grep "$BRANCH_NAME") ]]; then
      git checkout "$BRANCH_NAME"
    else
      git checkout -B "$BRANCH_NAME"
    fi
    cd $PARENT
  fi
done

for projectName in $MY_PROJECTS
do
  unset projectDesc
  declare -a projectDesc
  split_line projectDesc $projectName

  echo "========================= Add upstream for ${projectDesc[0]}"
  if [[ -d "$PARENT/${projectDesc[1]}" ]]; then
    cd "$PARENT/${projectDesc[1]}"
    git stash save
    if [[ $(git branch -a | grep "$BRANCH_NAME") ]]; then
      git checkout "$BRANCH_NAME"
    else
      git checkout -B "$BRANCH_NAME"
    fi
    cd $PARENT
  fi
done
