#!/bin/bash

if [[ -z "$1" ]]; then
  echo "please add commit message"
  exit
fi

PARENT=$(pwd)
TOOLS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$TOOLS_DIR/git-config"
source "$TOOLS_DIR/project-list"
if [[ -e $PARENT/git-config ]]; then
  source "$PARENT/git-config"
fi
if [[ -e $PARENT/project-list ]]; then
  source "$PARENT/project-list"
fi
  
for projectName in $MIFOSIO_PROJECTS
do
  echo "========================= Checking out develop branch: $projectName"
  if [[ -d $PARENT/$projectName ]]; then
    cd $PARENT/$projectName
    git add -A
    git commit -m "$1"
    git push
    cd $PARENT
  fi
done

for projectName in $MY_PROJECTS
do
  echo "========================= Checking out develop branch: $projectName"
  if [[ -d $PARENT/$projectName ]]; then
    cd $PARENT/$projectName
    git add -A
    git commit -m "$1"
    git push
    cd $PARENT
  fi
done
