#!/bin/bash

if [[ -z "$1" ]]; then
  echo "please add commit message"
  exit
fi

PARENT=$(pwd)
TOOLS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$TOOLS_DIR/splitter"
source "$TOOLS_DIR/git-config"
source "$TOOLS_DIR/project-list"
if [[ -e $PARENT/git-config ]]; then
  source "$PARENT/git-config"
fi
if [[ -e $PARENT/project-list ]]; then
  source "$PARENT/project-list"
fi

for projectName in $PROJECTS
do
  unset projectDesc
  declare -a projectDesc
  split_line projectDesc $projectName

  echo "========================= Commit changes: ${projectDesc[0]}"
  if [[ -d "$PARENT/${projectDesc[1]}" ]]; then
    cd "$PARENT/${projectDesc[1]}"
    git add -A
    git commit -m "$1"
    cd $PARENT
  fi
done

for projectName in $MY_PROJECTS
do
  unset projectDesc
  declare -a projectDesc
  split_line projectDesc $projectName

  echo "========================= Commit changes: ${projectDesc[0]}"
  if [[ -d "$PARENT/${projectDesc[1]}" ]]; then
    cd "$PARENT/${projectDesc[1]}"
    git add -A
    git commit -m "$1"
    cd $PARENT
  fi
done
