#!/bin/bash

PARENT=$(pwd)
TOOLS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$TOOLS_DIR/git-config"
source "$TOOLS_DIR/project-list"

for projectName in $MIFOSIO_PROJECTS
do
  echo "========================= Init git flow for $projectName"
  if [[ -d $PARENT/$projectName ]]; then
    cd $PARENT/$projectName
    git flow init -d
    cd $PARENT
  fi
done

for projectName in $MY_PROJECTS
do
  echo "========================= Init git flow for $projectName"
  if [[ -d $PARENT/$projectName ]]; then
    cd $PARENT/$projectName
    git flow init -d
    cd $PARENT
  fi
done
