#!/bin/bash

if [[ -z "$1" ]]; then
  echo "please specify branch"
  exit
fi
BRANCH_NAME="$1"

PARENT=$(pwd)
TOOLS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$TOOLS_DIR/git-config"
source "$TOOLS_DIR/project-list"

for projectName in $MIFOSIO_PROJECTS
do
  echo "========================= Merge upstream/develop: $projectName"
  if [[ -d $PARENT/$projectName ]]; then
    cd $PARENT/$projectName
    git stash save
    if [[ $(git branch -a | grep "$BRANCH_NAME") ]]; then
      git checkout "$BRANCH_NAME"
    else
      git checkout -B "$BRANCH_NAME"
    fi
    git fetch upstream
    git merge --no-edit upstream/develop
    git push -u origin "$BRANCH_NAME"
    cd $PARENT
  fi
done
