#!/bin/bash

PARENT=$(pwd)
TOOLS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$TOOLS_DIR/splitter"
source "$TOOLS_DIR/git-config"
source "$TOOLS_DIR/project-list"

if [[ -e $PARENT/git-config ]]; then
  source "$PARENT/git-config"
fi
if [[ -e $PARENT/project-list ]]; then
  source "$PARENT/project-list"
fi

for projectName in $PROJECTS
do
  unset projectDesc
  declare -a projectDesc
  split_line projectDesc $projectName
  
  echo "========================= Merge upstream/develop: ${projectDesc[0]}"
  if [[ -d "$PARENT/${projectDesc[1]}" ]]; then
    cd "$PARENT/${projectDesc[1]}"
    git stash save
    git checkout develop || git checkout -b develop
    git fetch upstream
    git merge --no-edit upstream/develop
    git push -u origin develop
    cd $PARENT
  fi
done
