#!/bin/bash

if [[ -z "$1" ]]; then
  echo "please specify branch"
  exit
fi
BRANCH_NAME="$1"

PARENT=$(pwd)
TOOLS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$TOOLS_DIR/splitter"
source "$TOOLS_DIR/git-config"
source "$TOOLS_DIR/project-list"

for projectName in $PROJECTS
do
  unset projectDesc
  declare -a projectDesc
  split_line projectDesc $projectName
  
  echo "========================= Merge upstream/develop: ${projectDesc[0]}"
  if [[ -d "$PARENT/${projectDesc[1]}" ]]; then
    cd "$PARENT/${projectDesc[1]}"
    git stash save
    if [[ $(git branch -a | grep "$BRANCH_NAME") ]]; then
      git checkout "$BRANCH_NAME"
    else
      git checkout -B "$BRANCH_NAME"
    fi
    git fetch upstream
    git merge --no-edit upstream/develop && git push -u origin "$BRANCH_NAME"
    cd $PARENT
  fi
done
